# Generated by Django 3.1.6 on 2021-02-18 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.IntegerField(default=0, verbose_name='기수')),
                ('question', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interviewee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.IntegerField(default=0, verbose_name='기수')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='이름')),
                ('major', models.CharField(blank=True, choices=[('major', '전공자'), ('non_major', '비전공자'), ('double_major', '복수전공자')], max_length=50, null=True, verbose_name='전공여부')),
                ('intro', models.TextField(blank=True, null=True, verbose_name='썸네일용 간단한 소개')),
                ('image', models.ImageField(blank=True, null=True, upload_to='interview', verbose_name='썸네일용 사진')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='이름')),
                ('answer', models.TextField(blank=True, null=True)),
                ('asking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='interview.asking', verbose_name='질문')),
            ],
        ),
    ]
