# Generated by Django 3.1.6 on 2021-02-16 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.IntegerField(default=0)),
                ('question', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interviewee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('major', models.CharField(blank=True, choices=[('major', '전공자'), ('non_major', '비전공자'), ('double_major', '복수전공자')], max_length=50, null=True, verbose_name='is_major')),
                ('intro', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='interview')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('asking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='interview.asking')),
            ],
        ),
    ]
